const byId=id=>document.getElementById(id), token=()=>localStorage.getItem('cancionero_token')||'';
const status=byId('status'),books=byId('books'),results=byId('results'),reader=byId('reader'),content=byId('readerContent');
let searchEpoch=0,readerEpoch=0,readerToken='',activeController=null;
const element=(tag,text,className)=>{const el=document.createElement(tag);if(text!==undefined)el.textContent=text;if(className)el.className=className;return el;};
function authFailure(){byId('login').style.display='inline-block';books.replaceChildren();results.replaceChildren();closeReader();}
async function api(action,body){
  if(!token()){authFailure();throw new Error('Inicia sesión desde el Cancionero para acceder a los libros.');}
  const res=await fetch('/api/cancionero'+(body?'':'?action='+action),{method:body?'POST':'GET',headers:{Authorization:'Bearer '+token(),...(body?{'Content-Type':'application/json'}:{})},body:body?JSON.stringify({action,...body}):undefined,cache:'no-store'});
  const data=await res.json().catch(()=>({}));
  if(!res.ok){if(res.status===401||res.status===403)authFailure();throw new Error(data.error||'No se pudo cargar la Biblioteca. Intenta de nuevo.');}return data;
}
function readButton(bookId,page){const b=element('button',page?'📖 Leer esta página':'📖 Leer libro');b.type='button';b.onclick=()=>openReader(bookId,page);return b;}
async function catalog(){try{const data=await api('library-catalog');books.replaceChildren();for(const book of data.books){const card=element('article',undefined,'card');card.append(element('h3',book.title),element('p',book.author||'Biblioteca Tuna','muted'),element('p',[book.pages?book.pages+' páginas':null,(book.size/1000000).toFixed(1)+' MB'].filter(Boolean).join(' · '),'meta'),readButton(book.id));books.append(card);const option=element('option',book.title);option.value=book.id;byId('bookFilter').append(option);}status.textContent=data.books.length?data.books.length+' libros disponibles. Busca palabras o elige un libro para leer.':'Aún no hay libros. Administración puede agregarlos a la Biblioteca.';}catch(err){status.textContent=err.message;}}
function highlighted(text,query){const p=element('p');const terms=query.match(/[\p{L}\p{N}]+/gu)||[];const normalize=t=>t.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();for(const part of text.split(/(\s+)/)){const word=normalize(part);p.append(terms.some(t=>word.includes(normalize(t)))?element('mark',part):document.createTextNode(part));}return p;}
async function search(event){event?.preventDefault();const query=byId('query').value.trim();if(!query)return;const epoch=++searchEpoch;byId('searchButton').disabled=true;status.textContent='Buscando en los libros…';try{const data=await api('library-search',{query,bookId:byId('bookFilter').value});if(epoch!==searchEpoch)return;results.replaceChildren();byId('resultSection').hidden=false;for(const hit of data.results){const card=element('article',undefined,'result');card.append(element('h3',hit.title),element('div',hit.source+(hit.page?' · página '+hit.page:''),'meta'),highlighted(hit.text,query),readButton(hit.bookId,hit.page));results.append(card);}status.textContent=data.results.length?data.results.length+' fragmentos encontrados'+(data.results.length===30?' (mostramos los primeros 30).':'.'):'No encontramos esas palabras. Prueba con menos palabras o busca en otro libro.';}catch(err){if(epoch===searchEpoch)status.textContent=err.message;}finally{if(epoch===searchEpoch)byId('searchButton').disabled=false;}}
function closeReader(){if(document.fullscreenElement===reader)document.exitFullscreen().catch(()=>{});readerEpoch++;activeController?.abort();activeController=null;content.replaceChildren();byId('openBook').removeAttribute('href');if(reader.open)reader.close();}
async function openReader(bookId,page){closeReader();const epoch=readerEpoch;readerToken=token();reader.showModal();byId('readerTitle').textContent='Cargando libro…';byId('readerStatus').textContent='Preparando lectura…';try{const data=await api('library-open',{bookId});if(epoch!==readerEpoch||readerToken!==token())return;byId('readerTitle').textContent=data.book.title;const url=data.url+(page?'#page='+Math.max(1,Number(page)||1):'');byId('openBook').href=url;if(data.book.mimeType==='application/pdf'){const frame=element('iframe');frame.title=data.book.title;frame.referrerPolicy='no-referrer';frame.src=url;content.append(frame);byId('readerStatus').textContent=(page?'Página '+page+'. ':'')+'Si tu navegador no muestra el PDF, usa «Abrir aparte». Si el acceso vence, cierra y vuelve a abrir el libro.';}else{activeController=new AbortController();const res=await fetch(data.url,{signal:activeController.signal,cache:'no-store'});if(!res.ok)throw new Error('No se pudo abrir el libro. Vuelve a intentarlo.');const text=await res.text();if(epoch!==readerEpoch||readerToken!==token())return;content.append(element('pre',text));byId('readerStatus').textContent='Documento de texto.';}}catch(err){if(epoch!==readerEpoch||err.name==='AbortError')return;byId('readerStatus').textContent=err.message;}}
byId('searchForm').onsubmit=search;byId('closeReader').onclick=closeReader;reader.addEventListener('cancel',()=>closeReader());byId('fullscreen').onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await reader.requestFullscreen();}catch{byId('readerStatus').textContent='Este navegador no permite pantalla completa. Usa «Abrir aparte».';}};
document.querySelectorAll('[data-query]').forEach(b=>b.onclick=()=>{byId('query').value=b.dataset.query;search();});
window.addEventListener('storage',e=>{if(e.key==='cancionero_token'){searchEpoch++;authFailure();status.textContent='La sesión cambió. Vuelve a entrar desde el Cancionero.';}});
window.addEventListener('pageshow',()=>{if(reader.open&&readerToken!==token())authFailure();});catalog();
