import test from 'node:test';import assert from 'node:assert/strict';import {Writable} from 'node:stream';
import {handleMemberLibrary,handleMemberBook,searchLibrary} from '../lib/library-member.js';
const book={id:'book-1',title:'Buen tunar',author:'Autor',pages:100,size:100,filename:'tuna.pdf',mimeType:'application/pdf',originalPath:'private/original.pdf',chunksPath:'private/index.json'};
function fixture(){const store=new Map(),calls=[];let live=true,approved=true,available=true;const deps={kv:{get:async k=>store.get(k),set:async(k,v,o)=>{assert.equal(o.ex,3600);store.set(k,v);}},listBooks:async()=>available?[book]:[],getKnowledgeChunks:async()=>[{bookId:book.id,title:book.title,source:book.title,page:3,text:'Las rondas musicales son una tradición de la tuna.'}],getSessionUser:async(req,token)=>live&&(token==='member'||req.headers?.authorization==='Bearer member')?{token:'member',user:{approved}}:null,get:async(path,options)=>{calls.push({path,options});return{headers:new Headers(options.headers.Range?{'content-range':'bytes 0-4/100','content-length':'5'}:{'content-length':'5'}),stream:new ReadableStream({start(c){c.enqueue(Buffer.from('%PDF-'));c.close();}})}}};async function call(fn,req={}){const bytes=[],res=new Writable({write(c,e,done){bytes.push(c);done();}});res.status=n=>{res.code=n;return res;};res.json=v=>{res.body=v;res.end();return res;};res.setHeader=(k,v)=>{(res.headers??={})[k]=v;};await fn({method:'POST',headers:{authorization:'Bearer member'},...req},res,deps);return{code:res.code||200,body:res.body,headers:res.headers,bytes:Buffer.concat(bytes)};}return{call,store,calls,disable:()=>live=false,pending:()=>approved=false,remove:()=>available=false};}
test('búsqueda normaliza acentos, conserva tuna, filtra libro y agrupa páginas',()=>{const chunks=[{bookId:'a',title:'Libro',source:'Libro',page:1,text:'Tradición de la tuna: ronda musical.'},{bookId:'a',title:'Libro',page:1,text:'La tradición de ronda continúa.'},{bookId:'b',title:'Otro',page:2,text:'Canciones populares.'}];assert.equal(searchLibrary('tradicion',chunks).length,1);assert.equal(searchLibrary('tuna',chunks).length,1);assert.equal(searchLibrary('tradicion ronda',chunks)[0].bookId,'a');for(const q of ['xyz','de la'])assert.equal(searchLibrary(q,chunks).length,0);assert.equal(searchLibrary('tuna',chunks,'b').length,0);});
test('catálogo, búsqueda y lectura requieren sesión aprobada',async()=>{const f=fixture();for(const action of ['library-catalog','library-search','library-open'])assert.equal((await f.call(handleMemberLibrary,{headers:{},body:{action,query:'tuna',bookId:book.id}})).code,401);f.pending();assert.equal((await f.call(handleMemberLibrary,{body:{action:'library-catalog'}})).code,403);assert.equal((await f.call(handleMemberBook,{method:'GET',query:{bookId:book.id}})).code,403);assert.equal(f.calls.length,0);});
test('catálogo oculta rutas y búsqueda no necesita OpenAI ni cuota',async()=>{const f=fixture(),r=await f.call(handleMemberLibrary,{body:{action:'library-catalog'}});assert.equal(r.body.books[0].originalPath,undefined);assert.equal(r.body.books[0].chunksPath,undefined);const s=await f.call(handleMemberLibrary,{body:{action:'library-search',query:'tradicion'}});assert.equal(s.body.results[0].page,3);assert.equal(s.body.results[0].bookId,book.id);assert.equal(f.store.size,0);assert.equal((await f.call(handleMemberLibrary,{body:{action:'library-search',query:''}})).code,400);});
test('ticket limitado al libro revalida sesión; sirve PDF privado',async()=>{const f=fixture(),r=await f.call(handleMemberLibrary,{body:{action:'library-open',bookId:book.id}}),query=Object.fromEntries(new URL(r.body.url,'https://app.test').searchParams),pdf=await f.call(handleMemberBook,{method:'GET',headers:{},query});assert.equal(pdf.bytes.toString(),'%PDF-');assert.equal(pdf.headers['Cache-Control'],'private, no-store');assert.equal(f.calls[0].options.access,'private');for(const q of [{...query,bookId:'other'},{...query,ticket:'bad'}])assert.equal((await f.call(handleMemberBook,{method:'GET',headers:{},query:q})).code,401);f.disable();assert.equal((await f.call(handleMemberBook,{method:'GET',headers:{},query})).code,401);});
test('rangos validan límites y conservan Content-Range',async()=>{const f=fixture(),r=await f.call(handleMemberBook,{method:'GET',query:{bookId:book.id},headers:{authorization:'Bearer member',range:'bytes=0-4'}});assert.equal(r.code,206);assert.equal(r.headers['Content-Range'],'bytes 0-4/100');assert.equal(f.calls[0].options.headers.Range,'bytes=0-4');for(const range of ['bytes=100-','bytes=9-1','bytes=-0','bytes=0-1,3-4','bad'])assert.equal((await f.call(handleMemberBook,{method:'GET',query:{bookId:book.id},headers:{authorization:'Bearer member',range}})).code,416);});
test('eliminar libro o vencer ticket impide lectura',async()=>{const f=fixture(),r=await f.call(handleMemberLibrary,{body:{action:'library-open',bookId:book.id}}),query=Object.fromEntries(new URL(r.body.url,'https://app.test').searchParams);f.remove();assert.equal((await f.call(handleMemberBook,{method:'GET',headers:{},query})).code,404);assert.equal(f.calls.length,0);f.store.clear();assert.equal((await f.call(handleMemberBook,{method:'GET',headers:{},query})).code,401);});
test('catálogo y apertura generan metadatos/ticket sin descargar PDFs ni índices',async()=>{const f=fixture();await f.call(handleMemberLibrary,{body:{action:'library-catalog'}});await f.call(handleMemberLibrary,{body:{action:'library-open',bookId:book.id}});assert.equal(f.calls.length,0);});
